app: 
  name: follow-up
server:
  url: 172.18.31.238
provider: 
  use: vllm
vllm:
  chat_model:
    source: unsloth/granite-4.0-micro-unsloth-bnb-4bit
    url: http://${server.url}:8000
    name: chat_agent
    path: ./models/modelfiles/chat_followup_modelfile.json
  extractor_model:
    source: unsloth/granite-4.0-micro-unsloth-bnb-4bit
    url: http://${server.url}:8000
    name: extractor_expert
    path: ./models/modelfiles/extractor_followup_modelfile.json
  translate_model:
    source: unsloth/granite-4.0-micro-unsloth-bnb-4bit
    url: http://${server.url}:8000
    name: translate_expert
    path: ./models/modelfiles/translate_modelfile.json
ollama:
  # base url of ollama
  url: http://${server.url}:11434
  chat_model:
    source: granite4:latest
    name: chat_agent
    path: ./models/modelfiles/chat_modelfile.json
  extractor_model:
    source: granite4:latest
    name: extractor_expert
    path: ./models/modelfiles/extractor_modelfile.json
  translate_model:
    source: granite4:latest
    name: translate_expert
    path: ./models/modelfiles/translate_modelfile.json
  embedding_model:
    source: embeddinggemma:latest
  generate_training_model: gpt-oss:20b
database:
  is_db: True
  # host che nel caso di podman compose è il nome del servizio
  postgres_server: 172.18.30.77
  sqlserver_server: srvlayer
  sqlserver_db_name: AI_REPO
  sqlserver_user: ai_repo
  sqlserver_password: ${oc.env:SQLSERVER_PASSWORD}
  sqlserver_conn: DRIVER={ODBC Driver 18 for SQL Server};SERVER=${.sqlserver_server};DATABASE=${.sqlserver_db_name};UID=${.sqlserver_user};PWD=${.sqlserver_password};TrustServerCertificate=yes
  postgres_port: 5432
  postgres_db_name_msg: msgdb
  postgres_user: postgres
  postgres_password: ${oc.env:POSTGRES_PASSWORD}
  postgres_msg_conn: host=${.postgres_server} port=${.postgres_port} dbname=${.postgres_db_name_msg} user=${.postgres_user} password=${.postgres_password}
  postgres_msg_table: followups
  postgres_jobstore: postgresql://${.postgres_user}:${.postgres_password}@${.postgres_server}:${.postgres_port}/apscheduler_db
whatsapp:
  port: 6000
  access_token:  ${oc.env:ACCESS_TOKEN_FOLLOW_UP}
  verify_token: ${oc.env:VERIFY_TOKEN_FOLLOW_UP}
  version: v24.0
  phone_id: ${oc.env:PHONE_ID}
  url: https://graph.facebook.com/${.version}/${.phone_id}/messages
whisper:
  model: small
info:
  # ambiente: TEST/PROD
  env: PROD
  # salvare le chat in formato csv dentro alla cartella history
  save_chat: False
  # per salvare i dati in un csv per fare un report dei messaggi inviati
  save_for_report: False 

